
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA ID INT LBRACE LBRACK LPAREN NUM RBRACE RBRACK RETURN RPAREN SEMI VOIDprogram : decl_listdecl_list : decl_list decl\n                | decldecl : var_decl\n            | func_decltype_spec : INT\n                | VOIDparams : param_list\n             | VOID\n             | param_list : param_list COMMA param\n                 | paramparam : type_spec ID\n            | type_spec ID LBRACK RBRACKfunc_decl : type_spec ID LPAREN params RPAREN LBRACE var_decls stmt_list RBRACEvar_decl : type_spec ID SEMI\n                | type_spec ID LBRACK NUM RBRACK SEMIvar_decls : var_decls var_decl\n                | stmt_list : stmt_list stmt\n                | stmt : expr_stmt\n           | return_stmtexpr_stmt : expr SEMI\n                | SEMIreturn_stmt : RETURN expr SEMI\n                  | RETURN SEMIexpr : ID ASSIGN expr\n           | ID LBRACK expr RBRACK\n           | ID LPAREN args RPAREN\n           | ID\n           | NUMargs : arg_list\n           | arg_list : arg_list COMMA expr\n                | expr'
    
_lr_action_items = {'INT':([0,2,3,4,5,9,11,13,23,24,26,29,32,35,],[7,7,-3,-4,-5,-2,-16,7,7,-17,-19,7,-18,-15,]),'VOID':([0,2,3,4,5,9,11,13,23,24,26,29,32,35,],[8,8,-3,-4,-5,-2,-16,18,8,-17,-19,8,-18,-15,]),'$end':([1,2,3,4,5,9,11,24,35,],[0,-1,-3,-4,-5,-2,-16,-17,-15,]),'ID':([6,7,8,11,15,18,24,26,29,30,31,32,36,37,38,40,41,43,44,45,46,48,54,57,],[10,-6,-7,-16,21,-7,-17,-19,-21,33,34,-18,-20,-22,-23,-25,34,34,34,34,-24,-27,-26,34,]),'SEMI':([10,11,20,24,26,29,31,32,33,34,36,37,38,39,40,41,42,46,47,48,49,54,55,56,],[11,-16,24,-17,-19,-21,40,-18,11,-31,-20,-22,-23,46,-25,48,-32,-24,54,-27,-28,-26,-29,-30,]),'LBRACK':([10,21,33,34,],[12,25,12,44,]),'LPAREN':([10,34,],[13,45,]),'RBRACE':([11,24,26,29,31,32,36,37,38,40,46,48,54,],[-16,-17,-19,-21,35,-18,-20,-22,-23,-25,-24,-27,-26,]),'RETURN':([11,24,26,29,31,32,36,37,38,40,46,48,54,],[-16,-17,-19,-21,41,-18,-20,-22,-23,-25,-24,-27,-26,]),'NUM':([11,12,24,26,29,31,32,36,37,38,40,41,43,44,45,46,48,54,57,],[-16,14,-17,-19,-21,42,-18,-20,-22,-23,-25,42,42,42,42,-24,-27,-26,42,]),'RPAREN':([13,16,17,18,19,21,27,28,34,42,45,49,51,52,53,55,56,58,],[-10,22,-8,-9,-12,-13,-11,-14,-31,-32,-34,-28,56,-33,-36,-29,-30,-35,]),'RBRACK':([14,25,34,42,49,50,55,56,],[20,28,-31,-32,-28,55,-29,-30,]),'COMMA':([17,19,21,27,28,34,42,49,52,53,55,56,58,],[23,-12,-13,-11,-14,-31,-32,-28,57,-36,-29,-30,-35,]),'LBRACE':([22,],[26,]),'ASSIGN':([34,],[43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'decl_list':([0,],[2,]),'decl':([0,2,],[3,9,]),'var_decl':([0,2,29,],[4,4,32,]),'func_decl':([0,2,],[5,5,]),'type_spec':([0,2,13,23,29,],[6,6,15,15,30,]),'params':([13,],[16,]),'param_list':([13,],[17,]),'param':([13,23,],[19,27,]),'var_decls':([26,],[29,]),'stmt_list':([29,],[31,]),'stmt':([31,],[36,]),'expr_stmt':([31,],[37,]),'return_stmt':([31,],[38,]),'expr':([31,41,43,44,45,57,],[39,47,49,50,53,58,]),'args':([45,],[51,]),'arg_list':([45,],[52,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> decl_list','program',1,'p_program','lab4.py',160),
  ('decl_list -> decl_list decl','decl_list',2,'p_decl_list','lab4.py',172),
  ('decl_list -> decl','decl_list',1,'p_decl_list','lab4.py',173),
  ('decl -> var_decl','decl',1,'p_decl','lab4.py',181),
  ('decl -> func_decl','decl',1,'p_decl','lab4.py',182),
  ('type_spec -> INT','type_spec',1,'p_type_spec','lab4.py',187),
  ('type_spec -> VOID','type_spec',1,'p_type_spec','lab4.py',188),
  ('params -> param_list','params',1,'p_params','lab4.py',193),
  ('params -> VOID','params',1,'p_params','lab4.py',194),
  ('params -> <empty>','params',0,'p_params','lab4.py',195),
  ('param_list -> param_list COMMA param','param_list',3,'p_param_list','lab4.py',203),
  ('param_list -> param','param_list',1,'p_param_list','lab4.py',204),
  ('param -> type_spec ID','param',2,'p_param','lab4.py',212),
  ('param -> type_spec ID LBRACK RBRACK','param',4,'p_param','lab4.py',213),
  ('func_decl -> type_spec ID LPAREN params RPAREN LBRACE var_decls stmt_list RBRACE','func_decl',9,'p_func_decl','lab4.py',223),
  ('var_decl -> type_spec ID SEMI','var_decl',3,'p_var_decl','lab4.py',267),
  ('var_decl -> type_spec ID LBRACK NUM RBRACK SEMI','var_decl',6,'p_var_decl','lab4.py',268),
  ('var_decls -> var_decls var_decl','var_decls',2,'p_var_decls','lab4.py',283),
  ('var_decls -> <empty>','var_decls',0,'p_var_decls','lab4.py',284),
  ('stmt_list -> stmt_list stmt','stmt_list',2,'p_stmt_list','lab4.py',292),
  ('stmt_list -> <empty>','stmt_list',0,'p_stmt_list','lab4.py',293),
  ('stmt -> expr_stmt','stmt',1,'p_stmt','lab4.py',301),
  ('stmt -> return_stmt','stmt',1,'p_stmt','lab4.py',302),
  ('expr_stmt -> expr SEMI','expr_stmt',2,'p_expr_stmt','lab4.py',307),
  ('expr_stmt -> SEMI','expr_stmt',1,'p_expr_stmt','lab4.py',308),
  ('return_stmt -> RETURN expr SEMI','return_stmt',3,'p_return_stmt','lab4.py',316),
  ('return_stmt -> RETURN SEMI','return_stmt',2,'p_return_stmt','lab4.py',317),
  ('expr -> ID ASSIGN expr','expr',3,'p_expr','lab4.py',325),
  ('expr -> ID LBRACK expr RBRACK','expr',4,'p_expr','lab4.py',326),
  ('expr -> ID LPAREN args RPAREN','expr',4,'p_expr','lab4.py',327),
  ('expr -> ID','expr',1,'p_expr','lab4.py',328),
  ('expr -> NUM','expr',1,'p_expr','lab4.py',329),
  ('args -> arg_list','args',1,'p_args','lab4.py',341),
  ('args -> <empty>','args',0,'p_args','lab4.py',342),
  ('arg_list -> arg_list COMMA expr','arg_list',3,'p_arg_list','lab4.py',350),
  ('arg_list -> expr','arg_list',1,'p_arg_list','lab4.py',351),
]
